env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
     - secure: "kEKxAxixWjqtwAgPfKQzABJ6wpnk+52l1gRMCp6H5OFbuQws+MrKAS4YO2CgGdfjufioQFIlExfoCbK4GD6CXp11HAO9p8YGgcJxT1cQ5TRXHbZhz96EayrXoKdUq4s+UCaZUbBQsSuMdpPFZojrk8TKj/mzv6B+dbFz4RJrG8o="
language: node_js
sudo: false
node_js:
 - "7.5.0"

addons:
  coverity_scan:
    project:
      name: "miguelleitao/osgjs"
      description: "Build submitted via Travis CI"
    notification_email: jml@meo.pt
    build_command: "--no-command --fs-capture-search ./sources/"
    branch_pattern: coverity_scan


install:
 - npm install
 - npm install -g npm@latest
 - npm install -g grunt
 - npm install -g grunt-cli

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then grunt check --verbose && grunt build --verbose && grunt test --verbose ; fi

pages:
  image: alpine
  before_script: 
    - apk update
    - apk add ttf-freefont graphviz
    - apk add doxygen
    - apk add git
  script:
    - doxygen doc/manual.cfg
    - mv doc/html public
    - cp doc/dris.png public/
  artifacts:
    paths:
    - public
  only:
  - master


notifications:
  webhooks:
    urls:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
